### ISSUE TITLE
Error when trying to install even as root

### ISSUE THREAD

**Issue by samhealey29** [b-mueller/apkx#3]
Hi,

receiving the following error when trying to install:

./install.sh: 3: ./install.sh: [[: not found

JRE and JDK installed and added to PATH.

Running Ubuntu 17.04

Any ideas?

Thanks

**Comment by benbaer** [comment]
Hi,
this "workaround" worked for me:
go to the apkx-direktory and open the install.sh-File using an editor of your choice (e.g. vim)
Delete the if-Statement, that there is only 
"
#!/bin/sh
cp apkx ...
chmod 755 ...
"
left.
Safe and run the Skript with sudo

**Comment by kj0317** [comment]
> Hi,
> this "workaround" worked for me:
> go to the apkx-direktory and open the install.sh-File using an editor of your choice (e.g. vim)
> Delete the if-Statement, that there is only
> "
> #!/bin/sh
> cp apkx ...
> chmod 755 ...
> "
> left.
> Safe and run the Skript with sudo

This worked for me also as a workaround.

**Comment by vivek-modi** [comment]
in window 

#!/bin/sh
cp apkx apkx-libs.jar enjarify.pex /usr/local/bin  
chmod 755 /usr/local/bin/apkx /usr/local/bin/enjarify.pex

Its Not Working Please help

**Comment by rcd27** [comment]
> in window
> 
> #!/bin/sh
> cp apkx apkx-libs.jar enjarify.pex /usr/local/bin
> chmod 755 /usr/local/bin/apkx /usr/local/bin/enjarify.pex
> 
> Its Not Working Please help

What exactly is not working? What are you doing?
