### ISSUE TITLE
Apkx not install in cmd

### ISSUE THREAD

**Issue by vivek-modi** [b-mueller/apkx#4]
'apkx' is not recognized as an internal or external command,
operable program or batch file.

How can be fixed in terminal..
I already install JRE and set path
also in my machine python 3+ version install

**Comment by rcd27** [comment]
Have you run `install.sh`?

**Comment by vivek-modi** [comment]
yes i install but nothing work

**Comment by rcd27** [comment]
> yes i install but nothing work

Edit it by deleting `if` statement:
```
  cp apkx apkx-libs.jar enjarify.pex /usr/local/bin  
  chmod 755 /usr/local/bin/apkx /usr/local/bin/enjarify.pex
```
